# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d429d39a05f78f18c90cbe372cc271e7"
name = "MyStore"
handle = "mystore-78"
application_url = "https://working-intended-parking-act.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://working-intended-parking-act.trycloudflare.com/auth/callback", "https://working-intended-parking-act.trycloudflare.com/auth/shopify/callback", "https://working-intended-parking-act.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
